Added button to exit customization page
grey-software/Material-Math pull request #73
Opened 2020-10-23 10:29 UTC by soumyankar

Fixes #69 
I hope the design of the button is satisfactory.

2020-10-23 10:47 UTC, milindvishnoi commented on packages/app/src/pages/CustomizePracticePage.vue
> +                label="Stop"
Please change the label to "close".

2020-10-23 10:48 UTC, milindvishnoi requested changes
Great job on the PR!

Please also increase the width of both the buttons, they look a bit too small.

2020-10-23 11:01 UTC, soumyankar commented
I've changed the button sizes and changed the label as well! 😄

2020-10-23 12:39 UTC, ArsalaBangash commented
@soumyankar I think 'exit' would be a better label than close :)

2020-10-23 14:18 UTC, soumyankar commented
> @soumyankar I think 'exit' would be a better label than close :)

Done!

2020-10-24 08:11 UTC, ArsalaBangash approved these changes
Excellent!

2020-10-24 08:11 UTC, merged