SVG Refactor + Icon Hotfix
grey-software/Material-Math pull request #83
Opened 2020-11-03 22:16 UTC by diracs-delta

# Summary

- call `vue-svg-loader` via webpack to import SVGs as Vue components. this also optimizes SVGs in the build process, greatly improving load times of SVG assets. (will extend this to other SVG assets later)
- extensively refactor PracticeCard to use the QCard component shipped with Quasar.
- fix spacing and margin issues, resolves #77 
- preserves current UI and appearance

# Preview

![20201103-141528](https://user-images.githubusercontent.com/44106031/98046427-0f81a800-1ddf-11eb-99b9-8908800033ca.png)

2020-11-04 19:45 UTC, ArsalaBangash commented on src/components/PracticeCard.vue
> +import BasicDiffIcon from "../assets/difficulty_icons/basic.svg"
I think BasicIcon gets the point across

2020-11-04 19:47 UTC, ArsalaBangash requested changes
## Solid iteration

Great work! Here are some points I have:

- [x] Realign the spacing in the customize practice card

### How it was before

<img width="402" alt="image" src="https://user-images.githubusercontent.com/19757203/98160423-ffadb500-1eff-11eb-8c79-48dafb7de031.png">


### How it is now

<img width="383" alt="image" src="https://user-images.githubusercontent.com/19757203/98160354-e60c6d80-1eff-11eb-9226-11ccbc410c4c.png">


- [x] We use the kebab-case notation for directories, so let's rename assets//difficulty_icons to assets/difficulty-icons/
- [x] I think CustomizePracticeCard or CustomizePractice would be a better name for the component since PracticeCard implies it's a card component where the practice occurs

2020-11-04 19:47 UTC, ArsalaBangash commented on src/components/PracticeCard.vue
> +    icon: {
Is this prop being used?

2020-11-05 20:21 UTC, diracs-delta commented on src/components/PracticeCard.vue
> +import BasicDiffIcon from "../assets/difficulty_icons/basic.svg"
done

2020-11-05 20:28 UTC, diracs-delta commented on src/components/PracticeCard.vue
> +    icon: {
nope. removed

2020-11-07 08:54 UTC, ArsalaBangash approved these changes
Great work!

2020-11-07 08:54 UTC, merged